// Mocks generated by Mockito 5.4.6 from annotations
// in tdd_chores/test/chores/domain/chores_domain_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tdd_chores/features/chores/domain/entities/group_chore.dart'
    as _i5;
import 'package:tdd_chores/features/chores/domain/entities/single_chore.dart'
    as _i4;
import 'package:tdd_chores/features/chores/domain/repositories/repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChoreRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChoreRepository extends _i1.Mock implements _i2.ChoreRepository {
  MockChoreRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.SingleChoreEntity>> getSingleChores() =>
      (super.noSuchMethod(
            Invocation.method(#getSingleChores, []),
            returnValue: _i3.Future<List<_i4.SingleChoreEntity>>.value(
              <_i4.SingleChoreEntity>[],
            ),
          )
          as _i3.Future<List<_i4.SingleChoreEntity>>);

  @override
  _i3.Future<void> addSingleChore(_i4.SingleChoreEntity? chore) =>
      (super.noSuchMethod(
            Invocation.method(#addSingleChore, [chore]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSingleChore(_i4.SingleChoreEntity? chore) =>
      (super.noSuchMethod(
            Invocation.method(#updateSingleChore, [chore]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSingleChore(_i4.SingleChoreEntity? chore) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSingleChore, [chore]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.GroupChoreEntity>> getGroupChores() =>
      (super.noSuchMethod(
            Invocation.method(#getGroupChores, []),
            returnValue: _i3.Future<List<_i5.GroupChoreEntity>>.value(
              <_i5.GroupChoreEntity>[],
            ),
          )
          as _i3.Future<List<_i5.GroupChoreEntity>>);

  @override
  _i3.Future<void> addGroupChore(_i5.GroupChoreEntity? groupChore) =>
      (super.noSuchMethod(
            Invocation.method(#addGroupChore, [groupChore]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateGroupChore(_i5.GroupChoreEntity? groupChore) =>
      (super.noSuchMethod(
            Invocation.method(#updateGroupChore, [groupChore]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteGroupChore(_i5.GroupChoreEntity? groupChore) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGroupChore, [groupChore]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
