// Mocks generated by Mockito 5.4.6 from annotations
// in tdd_chores/test/chores/data/chore_repository_impl.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tdd_chores/features/chores/data/datasources/remote/chore_firebase_service.dart'
    as _i2;
import 'package:tdd_chores/features/chores/data/models/group_chore.dart' as _i5;
import 'package:tdd_chores/features/chores/data/models/single_chore.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChoreFirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChoreFirebaseService extends _i1.Mock
    implements _i2.ChoreFirebaseService {
  MockChoreFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addSingleChore(_i4.SingleChoreModel? chore) =>
      (super.noSuchMethod(
            Invocation.method(#addSingleChore, [chore]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.SingleChoreModel>> getSingleChores() =>
      (super.noSuchMethod(
            Invocation.method(#getSingleChores, []),
            returnValue: _i3.Future<List<_i4.SingleChoreModel>>.value(
              <_i4.SingleChoreModel>[],
            ),
          )
          as _i3.Future<List<_i4.SingleChoreModel>>);

  @override
  _i3.Future<void> updateSingleChore(_i4.SingleChoreModel? chore) =>
      (super.noSuchMethod(
            Invocation.method(#updateSingleChore, [chore]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSingleChore(_i4.SingleChoreModel? chore) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSingleChore, [chore]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.GroupChoreModel>> getGroupChores() =>
      (super.noSuchMethod(
            Invocation.method(#getGroupChores, []),
            returnValue: _i3.Future<List<_i5.GroupChoreModel>>.value(
              <_i5.GroupChoreModel>[],
            ),
          )
          as _i3.Future<List<_i5.GroupChoreModel>>);

  @override
  _i3.Future<void> addGroupChore(_i5.GroupChoreModel? chore) =>
      (super.noSuchMethod(
            Invocation.method(#addGroupChore, [chore]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateGroupChore(_i5.GroupChoreModel? chore) =>
      (super.noSuchMethod(
            Invocation.method(#updateGroupChore, [chore]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
